- become: yes
  hosts: all
  name: k8s-master-install
  tasks:
    - name: Swap off
      shell: swapoff -a
    - name: kubeadm images pull
      shell: kubeadm config images pull
    - name: kubeadm init
      shell: kubeadm init
    - name: Reload service kubelet and daemon
      shell: systemctl daemon-reload && systemctl restart kubelet
    - name: Create folder .kube
      shell: mkdir -p $HOME/.kube
    - name: Set config cluster
      shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - name: chown for config cluster
      shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Config packeges
      shell: modprobe br_netfilter ip_vs_rr ip_vs_wrr ip_vs_sh nf_conntrack_ipv4 ip_vs
    - name: Install Weave-net
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    - name: Install bash completion
      shell: apt install -y bash-completion && kubectl completion bash > /etc/bash_completion.d/kubectl
    - name: Create file Join
      shell: kubeadm token create --print-join-command >> /root/kubadm-join.sh
    - name: Delete kubadm-join.sh in localhost
      file:
        state: absent
        path: ./kubadm-join.sh
      delegate_to: localhost
    - name: ansible copy file from remote to local.
      fetch:
        src: /root/kubadm-join.sh
        dest: ./
        flat: yes
